services:
  # The Brain (Your Rust App)
  app:
    build: .
    container_name: jesus-app
    restart: always
    ports:
      - "3000:3000" # Assuming your Rust app listens on 8080

  # The Face (Nginx)
  website:
    image: nginx:alpine
    container_name: jesus-website
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    restart: always